# basic options
title: Always Believe You Are Special
author: Rockey Simmons
email: your-email@domain.com
description: Belief System Blog
twitter_username: Don't Have One
github_username: codenamerockey

# Build settings
markdown: kramdown
theme: minima
